meta:
    image: 'postgres:8.4'
    version: master
env:
    OBO_ONTOLOGIES: 1,2,3,4,5
    CHADO_DB_NAME: postgres
    CHADO_DB_HOST: localhost
    CHADO_DB_PORT: 5432
    CHADO_DB_USERNAME: postgres
    CHADO_DB_PASSWORD: postgres
    POSTGRES_PASSWORD: postgres
    GMOD_ROOT: /usr/share/gmod/
    PGDATA: /var/lib/postgresql/9.4/
prebuild:
    packages: |
        build-essential libpng-dev zlib1g zlib1g-dev build-essential make
        libpq-dev libperlio-gzip-perl libcapture-tiny-perl
        libtest-differences-perl libperlio-gzip-perl libdevel-size-perl
        libdbi-perl libjson-perl libjson-xs-perl libheap-perl
        libhash-merge-perl libdbd-pg-perl libio-string-perl libtest-most-perl
        libarray-compare-perl libconvert-binary-c-perl libgraph-perl
        libgraphviz-perl libsoap-lite-perl libsvg-perl libsvg-graph-perl
        libset-scalar-perl libsort-naturally-perl libxml-sax-perl
        libxml-twig-perl libxml-writer-perl libyaml-perl libgd2-xpm-dev curl
        xsltproc netcat
    commands:
        - curl -L http://cpanmin.us | perl - App::cpanminus
        - cpanm --force Test::More Heap::Simple Heap::Simple::XS DBIx::DBStag
        - cpanm DBI Digest::Crc32 Cache::Ref::FIFO URI::Escape HTML::Entities
          HTML::HeadParser HTML::TableExtract HTTP::Request::Common LWP
          XML::Parser XML::Parser::PerlSAX XML::SAX::Writer XML::Simple
          Data::Stag Error PostScript::TextBlock Spreadsheet::ParseExcel
          Algorithm::Munkres BioPerl Bio::GFF3::LowLevel::Parser File::Next CGI
          DBD::Pg SQL::Translator Digest::MD5 Text::Shellwords Module::Build
          Class::DBI Class::DBI::Pg Class::DBI::Pager Template
          Bio::Chado::Schema GD GO::Parser
        - mkdir -p $GMOD_ROOT
        - mkdir -p $PGDATA
build:
    urls:
        - https://github.com/GMOD/Chado/archive/${version}.tar.gz
    commands:
        - tar xfz ${version}.tar.gz
        - cd Chado-${version}/chado/
        - yes | perl Makefile.PL GMOD_ROOT=$GMOD_ROOT DEFAULTS=1 RECONFIGURE=1
        - make
        - make install
        - /host/chado-postgres-prebuild.sh postgres
        - gosu postgres pg_ctl -w start
        - echo "Stalling for DB"
        - while true; do nc -q 1 localhost 5432 > /dev/null && sleep 4 && break; sleep 1; done;
        - make load_schema
        - make prepdb
        - echo $OBO_ONTOLOGIES | make ontologies
        - pg_dump -h localhost -p 5432 -U postgres --no-owner --no-acl postgres > /host/${pkg}-${version}.sql
