webapollo2:
  build: .
  links:
   - db
  ports:
   - "8080:8080"
  volumes:
   - ./pyu_data:/data
  environment:
    WEBAPOLLO_DB_USERNAME: postgres
    WEBAPOLLO_DB_PASSWORD: password
    WEBAPOLLO_DB_DRIVER: "org.postgresql.Driver"
    WEBAPOLLO_DB_DIALECT: "org.hibernate.dialect.PostgresPlusDialect"
    WEBAPOLLO_DB_URI: "jdbc:postgresql://${DB_1_PORT_5432_TCP_ADDR}/postgres"
db:
  image: postgres
  environment:
    POSTGRES_PASSWORD: password

