version: '2'
services:
  proxy:
    image: nginx
    ports:
        - "80:80"
    links:
        - apollo
        - galaxy
    volumes:
        - "./nginx/conf:/etc/nginx/conf.d"
        - "./nginx/html:/var/www/html"
  galaxy:
    build: galaxy
    environment:
        NONUSE: nodejs,proftp,reports
        GALAXY_LOGGING: full
    volumes_from:
      - apollo
  apollo:
    image: gmod/apollo:stable
    links:
      - "apollo_db:db"
    environment:
      WEBAPOLLO_DB_USERNAME: postgres
      WEBAPOLLO_DB_PASSWORD: password
      WEBAPOLLO_DB_DRIVER: "org.postgresql.Driver"
      WEBAPOLLO_DB_DIALECT: "org.hibernate.dialect.PostgresPlusDialect"
      WEBAPOLLO_DB_URI: "jdbc:postgresql://db/postgres"
    volumes:
      - "./data:/data"
  apollo_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
  apollo_admin:
    build: apollo
    links:
        - apollo
    environment:
      ADMIN_USERNAME: admin@apollo.org
      ADMIN_FIRST_NAME: Galaxy
      ADMIN_LAST_NAME: Admin
      ADMIN_PASSWORD: admin
