galaxy:
    build: galaxy
    ports:
        - 80
    environment:
        NONUSE: nodejs,proftp,reports
        GALAXY_LOGGING: full
webapollo2:
  image: erasche/webapollo2:cpt
  links:
   - db
  ports:
   - 8080
  environment:
    WEBAPOLLO_DB_USERNAME: postgres
    WEBAPOLLO_DB_PASSWORD: password
    WEBAPOLLO_DB_DRIVER: "org.postgresql.Driver"
    WEBAPOLLO_DB_DIALECT: "org.hibernate.dialect.PostgresPlusDialect"
    WEBAPOLLO_DB_URI: "jdbc:postgresql://$${DB_1_PORT_5432_TCP_ADDR}/postgres"
db:
  image: postgres
  environment:
    POSTGRES_PASSWORD: password
