version: '2'
services:
  galaxy:
    build: galaxy
    ports:
        - 80
    environment:
        NONUSE: nodejs,proftp,reports
        GALAXY_LOGGING: full
    volumes_from:
      - apollo
  apollo:
    image: gmod/apollo:stable
    links:
      - "apollo_db:db"
    ports:
      - "8080"
    environment:
      WEBAPOLLO_DB_USERNAME: postgres
      WEBAPOLLO_DB_PASSWORD: password
      WEBAPOLLO_DB_DRIVER: "org.postgresql.Driver"
      WEBAPOLLO_DB_DIALECT: "org.hibernate.dialect.PostgresPlusDialect"
      WEBAPOLLO_DB_URI: "jdbc:postgresql://db/postgres"
    volumes:
      - "./data:/data"
  apollo_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
